# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2e1990a67fded5b287a3a42d186b017e04b35b27d01b5049a6e4b7737ff1d63780e2e6865948b9a64fd45eaa7c1ad0ac49d231d4ce4b292b917dea68c063626

test:
  secret_key_base: 2c4ee451cb31ec326c64e9d4533533e3becbff8d3998237acc45691d77cac63d1a65c67071ba53e132e582027660cab13578bb5fe050f0e731274d6f871ec283

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
